[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://unpkg.com https://cdn.tailwindcss.com https://connect.facebook.net https://www.facebook.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src https://www.youtube.com https://www.youtube-nocookie.com; img-src 'self' data: https:; connect-src 'self' https://hooks.zapier.com https://www.facebook.com https://connect.facebook.net;"
